name: Snyk example
on:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-python3.8@master
        with:
          go-version: '1.19'
      - name: Snyk test
        run: snyk code test --json > snyk_output.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload Snyk Test Result as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk_output.jso
