name: Snyk example

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk Code Test
        continue-on-error: true  # This step will not cause the workflow to fail
        run: snyk code test --json > snyk_output.json

      - name: Upload Snyk Test Result as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk_output.json

