name: Snyk example

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3 for the latest stable release

      - uses: snyk/actions/setup@master
        with:
          snyk-version: 'latest'  # Ensure you specify which version of Snyk to use

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4 for the latest stable release
        with:
          python-version: '3.8'  # Correctly specifying Python version
          
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk test
        run: snyk test --json

      - name: Upload Snyk Test Result as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk_output.json

